import { env } from "cloudflare:workers";
type Row = Record<string, any>;
const json = (data: unknown, status = 200, headers?: HeadersInit) => {
  const responseHeaders = new Headers(headers);
  responseHeaders.set("Cache-Control", "no-store, max-age=0");
  return Response.json(data, { status, headers: responseHeaders });
};
const now = () => new Date().toISOString();
const uid = () => crypto.randomUUID();
const sha = async (v: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(v)))).map(b => b.toString(16).padStart(2, "0")).join("");
const passwordHash = (email: string, password: string) => sha(`nfc-v1:${email.toLowerCase()}:${password}`);
const db = () => { if (!env.DB) throw new Error("Database is not available"); return env.DB; };
const n8nSecret = () => (env as unknown as Record<string,string|undefined>).N8N_WEBHOOK_SECRET;
const n8nWebhookUrl = () => (env as unknown as Record<string,string|undefined>).N8N_WEBHOOK_URL;
function requireN8n(request: Request) {
  const secret=n8nSecret(), supplied=request.headers.get("authorization");
  if(!secret||supplied!==`Bearer ${secret}`) throw Object.assign(new Error("Automation access denied"),{status:401});
}
const fail = (message: string, status = 400) => json({ error: message }, status);
const all = async (sql: string, ...bind: unknown[]) => (await db().prepare(sql).bind(...bind).all<Row>()).results;
const one = async (sql: string, ...bind: unknown[]) => (await db().prepare(sql).bind(...bind).first<Row>());
async function seed() {
  const settings=env as unknown as Record<string,string|undefined>;
  const email=settings.INITIAL_ADMIN_EMAIL?.trim().toLowerCase();
  const password=settings.INITIAL_ADMIN_PASSWORD;
  if(!email||!password||password.length<12)return;
  if(await one("SELECT id FROM users WHERE role='admin' LIMIT 1"))return;
  await db().prepare("INSERT INTO users (id,email,password_hash,name,role,active,created_at) VALUES (?,?,?,?, 'admin',1,?)")
    .bind(uid(),email,await passwordHash(email,password),settings.INITIAL_ADMIN_NAME?.trim()||"Clinic Admin",now()).run();
}
function cookie(request: Request, key: string) { return request.headers.get("cookie")?.split(";").map(v=>v.trim()).find(v=>v.startsWith(`${key}=`))?.slice(key.length+1); }
async function currentUser(request: Request) { const token=cookie(request,"clinic_session"); if(!token)return null; return one("SELECT u.id,u.email,u.name,u.role,u.specialty,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?",await sha(token),now()); }
function requireRole(user: Row|null, roles:string[]) { if(!user)throw Object.assign(new Error("Please sign in"),{status:401}); if(!roles.includes(user.role))throw Object.assign(new Error("You are not allowed to do that"),{status:403}); }
async function sendEmail(userId:string,kind:string,subject:string,body:string,appointmentId?:string,suffix="") {
  const dedupeKey=`${kind}:${appointmentId??userId}:${suffix}`;
  await db().prepare("INSERT OR IGNORE INTO email_events (id,appointment_id,user_id,kind,subject,body,dedupe_key,sent_at) VALUES (?,?,?,?,?,?,?,?)").bind(uid(),appointmentId??null,userId,kind,subject,body,dedupeKey,now()).run();
  const event=await one("SELECT e.id,e.kind,e.subject,e.body,e.delivery_status,u.email recipient_email,u.name recipient_name FROM email_events e JOIN users u ON u.id=e.user_id WHERE e.dedupe_key=?",dedupeKey);
  const webhook=n8nWebhookUrl(),secret=n8nSecret(),instantKinds=new Set(["confirmed","rejected","cancelled","leave_cancelled"]);
  if(event?.delivery_status==="queued"&&webhook&&secret&&instantKinds.has(kind)){
    try{
      await fetch(webhook,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${secret}`},body:JSON.stringify(event)});
    }catch{
      // The durable queue remains available for the scheduled n8n fallback.
    }
  }
}
async function runAutomations() {
  const stamp=now(), expired=await all("SELECT a.id,a.patient_id,u.name doctor_name,a.starts_at FROM appointments a JOIN users u ON u.id=a.doctor_id WHERE a.status='pending' AND a.starts_at<=?",stamp);
  for(const a of expired){await db().prepare("UPDATE appointments SET status='cancelled',cancel_reason='Not confirmed before start time',updated_at=? WHERE id=? AND status='pending'").bind(stamp,a.id).run();await sendEmail(a.patient_id,"expired","Appointment cancelled",`Your appointment with ${a.doctor_name} was not confirmed before its start time and has been cancelled.`,a.id);}
  const from=new Date(Date.now()+20*3600000).toISOString(),to=new Date(Date.now()+28*3600000).toISOString(),reminders=await all("SELECT a.id,a.patient_id,u.name doctor_name,a.starts_at FROM appointments a JOIN users u ON u.id=a.doctor_id WHERE a.status='confirmed' AND a.starts_at BETWEEN ? AND ?",from,to);
  for(const a of reminders)await sendEmail(a.patient_id,"reminder","Appointment reminder",`Reminder: your appointment with ${a.doctor_name} is at ${a.starts_at}.`,a.id,a.starts_at.slice(0,10));
  return {expired:expired.length,reminders:reminders.length};
}
const localIso=(date:string,time:string)=>new Date(`${date}T${time}:00+05:00`).toISOString();
const minutes=(t:string)=>{const[h,m]=t.split(":").map(Number);return h*60+m};
async function validSlot(doctorId:string,startsAt:string){
  const d=new Date(startsAt);if(!Number.isFinite(d.getTime())||d<=new Date())return "Past appointments cannot be booked";
  const date=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Karachi",year:"numeric",month:"2-digit",day:"2-digit"}).format(d),time=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Karachi",hour:"2-digit",minute:"2-digit",hour12:false}).format(d),day=new Date(`${date}T12:00:00Z`).getUTCDay();
  if(!await one("SELECT id FROM users WHERE id=? AND role='doctor' AND active=1",doctorId))return "Doctor is inactive or unavailable";
  if(await one("SELECT id FROM doctor_leave WHERE doctor_id=? AND leave_date=?",doctorId,date))return "Doctor is on leave that day";
  const hours=await all("SELECT start_time,end_time FROM doctor_hours WHERE doctor_id=? AND day_of_week=?",doctorId,day),start=minutes(time);
  if(!hours.some(h=>start>=minutes(h.start_time)&&start+30<=minutes(h.end_time)))return "Selected time is outside the doctor's working hours";
  if(start%30!==0)return "Appointments must start on a 30 minute slot"; return null;
}
export async function GET(request:Request){
 try{await seed();const url=new URL(request.url),action=url.searchParams.get("action")??"me",user=await currentUser(request);
  if(action==="n8n_queue"){requireN8n(request);const messages=await all("SELECT e.id,e.kind,e.subject,e.body,e.delivery_attempts,u.email recipient_email,u.name recipient_name FROM email_events e JOIN users u ON u.id=e.user_id WHERE e.delivery_status IN ('queued','failed') AND e.delivery_attempts<5 ORDER BY e.sent_at LIMIT 50");return json({messages})}
  if(action==="me")return json({user});
  if(action==="doctors")return json({doctors:await all("SELECT id,name,specialty FROM users WHERE role='doctor' AND active=1 ORDER BY name")});
  if(action==="availability"){const doctorId=url.searchParams.get("doctorId")??"",date=url.searchParams.get("date")??"";if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return fail("Choose a valid date");if(!await one("SELECT id FROM users WHERE id=? AND role='doctor' AND active=1",doctorId))return fail("Doctor is inactive or unavailable",404);const day=new Date(`${date}T12:00:00Z`).getUTCDay(),hrs=await all("SELECT start_time,end_time FROM doctor_hours WHERE doctor_id=? AND day_of_week=? ORDER BY start_time",doctorId,day);if(await one("SELECT id FROM doctor_leave WHERE doctor_id=? AND leave_date=?",doctorId,date))return json({slots:[]});const from=localIso(date,"00:00"),to=localIso(date,"23:59"),taken=await all("SELECT starts_at FROM appointments WHERE doctor_id=? AND status IN ('pending','confirmed') AND starts_at>=? AND starts_at<?",doctorId,from,to),patientTaken=user?.role==="patient"?await all("SELECT starts_at FROM appointments WHERE patient_id=? AND status IN ('pending','confirmed') AND starts_at>=? AND starts_at<?",user.id,from,to):[],busy=new Set([...taken,...patientTaken].map(x=>x.starts_at)),slots:string[]=[];for(const h of hrs)for(let m=minutes(h.start_time);m+30<=minutes(h.end_time);m+=30){const t=`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`,iso=localIso(date,t);if(new Date(iso)>new Date()&&!busy.has(iso))slots.push(iso)}return json({slots})}
  requireRole(user,["patient","doctor","admin"]);
  if(action==="appointments"){let q="SELECT a.*,p.name patient_name,p.email patient_email,d.name doctor_name,d.specialty FROM appointments a JOIN users p ON p.id=a.patient_id JOIN users d ON d.id=a.doctor_id",args:unknown[]=[];if(user.role==="patient"){q+=" WHERE a.patient_id=?";args=[user.id]}else if(user.role==="doctor"){q+=" WHERE a.doctor_id=?";args=[user.id]}q+=" ORDER BY a.starts_at DESC";const rows=await all(q,...args);if(user.role==="admin")rows.forEach(r=>delete r.visit_note);return json({appointments:rows})}
  if(action==="appointment"){const id=url.searchParams.get("id")??"",appointment=await one("SELECT a.*,p.name patient_name,p.email patient_email,d.name doctor_name,d.specialty FROM appointments a JOIN users p ON p.id=a.patient_id JOIN users d ON d.id=a.doctor_id WHERE a.id=?",id);if(!appointment)return fail("Appointment not found",404);if(user.role==="patient"&&appointment.patient_id!==user.id)return fail("You cannot access another patient's appointment",403);if(user.role==="doctor"&&appointment.doctor_id!==user.id)return fail("You cannot access another doctor's appointment",403);if(user.role==="admin")delete appointment.visit_note;return json({appointment})}
  if(action==="history"){requireRole(user,["doctor"]);const patientId=url.searchParams.get("patientId")??"";if(!await one("SELECT id FROM appointments WHERE doctor_id=? AND patient_id=? LIMIT 1",user.id,patientId))return fail("You cannot access another doctor's patient history",403);return json({history:await all("SELECT a.id,a.starts_at,a.status,a.visit_note,p.name patient_name FROM appointments a JOIN users p ON p.id=a.patient_id WHERE a.doctor_id=? AND a.patient_id=? AND a.starts_at<=? ORDER BY a.starts_at DESC",user.id,patientId,now())})}
  if(action==="visit_note"){requireRole(user,["patient","doctor"]);const id=url.searchParams.get("id")??"",appointment=await one("SELECT id,patient_id,doctor_id,visit_note FROM appointments WHERE id=?",id);if(!appointment)return fail("Appointment not found",404);if(user.role==="patient"&&appointment.patient_id!==user.id)return fail("You cannot access another patient's visit note",403);if(user.role==="doctor"&&appointment.doctor_id!==user.id)return fail("You cannot access another doctor's visit note",403);return json({visitNote:appointment.visit_note})}
  if(action==="hours"){requireRole(user,["doctor"]);return json({hours:await all("SELECT * FROM doctor_hours WHERE doctor_id=? ORDER BY day_of_week,start_time",user.id),leave:await all("SELECT * FROM doctor_leave WHERE doctor_id=? ORDER BY leave_date",user.id)})}
  if(action==="dashboard"){requireRole(user,["admin"]);const doctors=await all("SELECT d.id,d.name,d.specialty,d.active,SUM(CASE WHEN a.status='pending' THEN 1 ELSE 0 END) pending,SUM(CASE WHEN a.status='confirmed' THEN 1 ELSE 0 END) confirmed,SUM(CASE WHEN a.status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN a.status='no_show' THEN 1 ELSE 0 END) no_show,SUM(CASE WHEN a.status IN ('cancelled','rejected') THEN 1 ELSE 0 END) cancelled FROM users d LEFT JOIN appointments a ON a.doctor_id=d.id WHERE d.role='doctor' GROUP BY d.id ORDER BY d.name"),today=await all("SELECT a.id,a.starts_at,a.status,p.name patient_name,d.name doctor_name FROM appointments a JOIN users p ON p.id=a.patient_id JOIN users d ON d.id=a.doctor_id WHERE date(a.starts_at,'+5 hours')=date('now','+5 hours') ORDER BY a.starts_at");return json({doctors,today})}
  if(action==="outbox")return json({emails:await all("SELECT id,kind,subject,body,sent_at FROM email_events WHERE user_id=? ORDER BY sent_at DESC LIMIT 30",user.id)});
  return fail("Unknown action",404);
 }catch(e:any){return fail(e.message||"Request failed",e.status||500)}
}
export async function POST(request:Request){
 try{await seed();const body=await request.json() as Row,action=String(body.action||""),user=await currentUser(request);
  if(action==="n8n_run"){requireN8n(request);return json(await runAutomations())}
  if(action==="n8n_mark_sent"){requireN8n(request);const result=await db().prepare("UPDATE email_events SET delivery_status='sent',delivery_attempts=delivery_attempts+1,delivered_at=?,last_error=NULL WHERE id=? AND delivery_status!='sent'").bind(now(),String(body.id||"")).run();return json({ok:true,changed:result.meta.changes})}
  if(action==="n8n_mark_failed"){requireN8n(request);const message=String(body.error||"Gmail delivery failed").slice(0,500);const result=await db().prepare("UPDATE email_events SET delivery_status='failed',delivery_attempts=delivery_attempts+1,last_error=? WHERE id=? AND delivery_status!='sent'").bind(message,String(body.id||"")).run();return json({ok:true,changed:result.meta.changes})}
  if(action==="login"){const email=String(body.email||"").trim().toLowerCase(),found=await one("SELECT * FROM users WHERE email=? AND active=1",email);if(!found||found.password_hash!==await passwordHash(email,String(body.password||"")))return fail("Email or password is incorrect",401);const token=`${uid()}${uid()}`,expires=new Date(Date.now()+7*86400000).toISOString();await db().prepare("INSERT INTO sessions (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").bind(await sha(token),found.id,expires,now()).run();return json({user:{id:found.id,email:found.email,name:found.name,role:found.role,specialty:found.specialty}},200,{"Set-Cookie":`clinic_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800`})}
  if(action==="signup"){const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(name.length<2||!email.includes("@")||password.length<8)return fail("Enter a name, valid email, and password of at least 8 characters");try{await db().prepare("INSERT INTO users (id,email,password_hash,name,role,active,created_at) VALUES (?,?,?,?, 'patient',1,?)").bind(uid(),email,await passwordHash(email,password),name,now()).run()}catch{return fail("An account with that email already exists",409)}return json({ok:true},201)}
  if(action==="logout"){const token=cookie(request,"clinic_session");if(token)await db().prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(token)).run();return json({ok:true},200,{"Set-Cookie":"clinic_session=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax"})}
  if(action==="set_password"){const token=String(body.token||""),invite=await one("SELECT i.*,u.email FROM invitations i JOIN users u ON u.id=i.user_id WHERE i.token_hash=? AND i.used_at IS NULL AND i.expires_at>?",await sha(token),now());if(!invite)return fail("Invitation is invalid or expired");if(String(body.password||"").length<8)return fail("Password must be at least 8 characters");await db().batch([db().prepare("UPDATE users SET password_hash=? WHERE id=?").bind(await passwordHash(invite.email,String(body.password)),invite.user_id),db().prepare("UPDATE invitations SET used_at=? WHERE token_hash=?").bind(now(),invite.token_hash)]);return json({ok:true})}
  requireRole(user,["patient","doctor","admin"]);
  if(action==="book"){requireRole(user,["patient"]);const doctorId=String(body.doctorId||""),startsAt=String(body.startsAt||""),err=await validSlot(doctorId,startsAt);if(err)return fail(err);if(await one("SELECT id FROM appointments WHERE doctor_id=? AND starts_at=? AND status IN ('pending','confirmed')",doctorId,startsAt))return fail("This doctor slot has just been booked. Please choose another time.",409);if(await one("SELECT id FROM appointments WHERE patient_id=? AND starts_at=? AND status IN ('pending','confirmed')",user.id,startsAt))return fail("You already have an appointment at this time.",409);try{await db().prepare("INSERT INTO appointments (id,patient_id,doctor_id,starts_at,ends_at,status,created_at,updated_at) VALUES (?,?,?,?,?,'pending',?,?)").bind(uid(),user.id,doctorId,startsAt,new Date(new Date(startsAt).getTime()+1800000).toISOString(),now(),now()).run()}catch{return fail("The selected time is no longer available. Refresh and choose another slot.",409)}return json({ok:true,appointment:{doctorId,startsAt,status:"pending"}},201)}
  if(action==="appointment_status"){requireRole(user,["doctor"]);const a=await one("SELECT * FROM appointments WHERE id=?",body.id);if(!a||a.doctor_id!==user.id)return fail("Appointment not found or does not belong to you",403);const next=String(body.status);if(["confirmed","rejected"].includes(next)){if(a.status!=="pending")return fail("Only a pending request can be confirmed or rejected");await db().prepare("UPDATE appointments SET status=?,cancel_reason=?,updated_at=? WHERE id=?").bind(next,next==="rejected"?"Rejected by doctor":null,now(),a.id).run();await sendEmail(a.patient_id,next,next==="confirmed"?"Appointment confirmed":"Appointment rejected",`Your appointment on ${a.starts_at} was ${next}.`,a.id)}else if(["completed","no_show"].includes(next)){if(new Date(a.starts_at)>new Date())return fail("A future appointment cannot be completed or marked no-show");if(!["confirmed","pending"].includes(a.status))return fail("This visit cannot be updated");await db().prepare("UPDATE appointments SET status=?,visit_note=?,updated_at=? WHERE id=?").bind(next,String(body.note||"").trim()||null,now(),a.id).run()}else return fail("Invalid status");return json({ok:true})}
  if(action==="cancel"){requireRole(user,["patient"]);const a=await one("SELECT * FROM appointments WHERE id=? AND patient_id=?",body.id,user.id);if(!a)return fail("Appointment not found",404);if(new Date(a.starts_at).getTime()-Date.now()<7200000)return fail("Appointments cannot be cancelled within 2 hours of the start time");if(!["pending","confirmed"].includes(a.status))return fail("This appointment cannot be cancelled");await db().prepare("UPDATE appointments SET status='cancelled',cancel_reason='Cancelled by patient',updated_at=? WHERE id=?").bind(now(),a.id).run();await sendEmail(user.id,"cancelled","Appointment cancelled",`Your appointment on ${a.starts_at} was cancelled.`,a.id);return json({ok:true})}
  if(action==="reschedule"){requireRole(user,["patient"]);const a=await one("SELECT * FROM appointments WHERE id=? AND patient_id=?",body.id,user.id);if(!a)return fail("Appointment not found",404);if(new Date(a.starts_at).getTime()-Date.now()<7200000)return fail("Appointments cannot be rescheduled within 2 hours");const startsAt=String(body.startsAt||""),err=await validSlot(a.doctor_id,startsAt);if(err)return fail(err);try{await db().prepare("UPDATE appointments SET starts_at=?,ends_at=?,status='pending',updated_at=? WHERE id=?").bind(startsAt,new Date(new Date(startsAt).getTime()+1800000).toISOString(),now(),a.id).run()}catch{return fail("That slot is no longer available, or it conflicts with another appointment",409)}return json({ok:true})}
  if(action==="add_hours"){requireRole(user,["doctor"]);const day=Number(body.dayOfWeek),start=String(body.startTime),end=String(body.endTime);if(!Number.isInteger(day)||day<0||day>6||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||minutes(end)<=minutes(start))return fail("End time must be after start time");if(await one("SELECT id FROM doctor_hours WHERE doctor_id=? AND day_of_week=? AND start_time<? AND end_time>?",user.id,day,end,start))return fail("These hours overlap an existing schedule");await db().prepare("INSERT INTO doctor_hours (id,doctor_id,day_of_week,start_time,end_time) VALUES (?,?,?,?,?)").bind(uid(),user.id,day,start,end).run();return json({ok:true},201)}
  if(action==="add_leave"){requireRole(user,["doctor"]);const date=String(body.date||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(`${date}T23:59:59+05:00`)<new Date())return fail("Leave day cannot be in the past");try{await db().prepare("INSERT INTO doctor_leave (id,doctor_id,leave_date,reason,created_at) VALUES (?,?,?,?,?)").bind(uid(),user.id,date,String(body.reason||"Leave"),now()).run()}catch{return fail("That leave day already exists",409)}const affected=await all("SELECT id,patient_id,starts_at FROM appointments WHERE doctor_id=? AND status IN ('pending','confirmed') AND starts_at>=? AND starts_at<?",user.id,localIso(date,"00:00"),localIso(date,"23:59"));for(const a of affected){await db().prepare("UPDATE appointments SET status='cancelled',cancel_reason='Doctor leave',updated_at=? WHERE id=?").bind(now(),a.id).run();await sendEmail(a.patient_id,"leave_cancelled","Appointment cancelled: doctor leave",`Your appointment on ${a.starts_at} was cancelled because the doctor is on leave.`,a.id)}return json({ok:true,cancelled:affected.length},201)}
  if(action==="add_doctor"){requireRole(user,["admin"]);const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),specialty=String(body.specialty||"").trim();if(!name||!email.includes("@")||!specialty)return fail("Name, valid email, and specialty are required");const userId=uid(),token=`${uid()}${uid()}`;try{await db().batch([db().prepare("INSERT INTO users (id,email,password_hash,name,role,specialty,active,created_at) VALUES (?,?,?,?, 'doctor',?,1,?)").bind(userId,email,await passwordHash(email,uid()),name,specialty,now()),db().prepare("INSERT INTO invitations (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").bind(await sha(token),userId,new Date(Date.now()+7*86400000).toISOString(),now())])}catch{return fail("A user with that email already exists",409)}await sendEmail(userId,"doctor_invite","Set your clinic password",`Welcome to Nowshera Family Clinic. Set your password using invitation token: ${token}`,undefined,userId);return json({ok:true,invitationToken:token},201)}
  if(action==="deactivate_doctor"){requireRole(user,["admin"]);await db().prepare("UPDATE users SET active=0 WHERE id=? AND role='doctor'").bind(body.doctorId).run();return json({ok:true})}
  if(action==="run_automations"){requireRole(user,["admin"]);return json(await runAutomations())}
  return fail("Unknown action",404);
 }catch(e:any){return fail(e.message||"Request failed",e.status||500)}
}
